import { PrismaClient } from '@prisma/client'
import { PrismaLibSql } from '@prisma/adapter-libsql'

const adapter = new PrismaLibSql({
  url: process.env.DATABASE_URL || 'file:./dev.db'
})

const prisma = new PrismaClient({
  adapter,
})

// Sample Malaysian citizenship applicants data (Borang B - Article 15(2))
const applicantsData = [
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'AHMAD BIN ABDULLAH',
    fullNameOther: null,
    gender: 'M',
    dateOfBirth: new Date('1995-03-15'),
    placeOfBirth: 'LONDON, UNITED KINGDOM',
    nationality: 'BRITISH',
    idType: 'PASSPORT',
    idNumber: 'PA1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'ABDULLAH BIN HASSAN',
    permAddress1: 'NO. 25, JALAN BUKIT BINTANG',
    permAddress2: 'TAMAN MAJU JAYA',
    permAddress3: null,
    permPostcode: '50200',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 25, JALAN BUKIT BINTANG',
    corresAddress2: 'TAMAN MAJU JAYA',
    corresPostcode: '50200',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BUJANG',
    occupation: 'JURUTERA',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2020-01-15'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'PA1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'SITI NURHALIZA BINTI MOHD RAZALI',
    fullNameOther: null,
    gender: 'F',
    dateOfBirth: new Date('1998-07-22'),
    placeOfBirth: 'SINGAPORE',
    nationality: 'SINGAPOREAN',
    idType: 'PASSPORT',
    idNumber: 'E1234567A',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'MOHD RAZALI BIN AHMAD',
    permAddress1: 'NO. 88, LORONG SETIA',
    permAddress2: 'TAMAN DESA HARMONI',
    permAddress3: null,
    permPostcode: '81100',
    permCity: 'JOHOR BAHRU',
    permState: 'JOHOR',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 88, LORONG SETIA',
    corresAddress2: 'TAMAN DESA HARMONI',
    corresPostcode: '81100',
    corresCity: 'JOHOR BAHRU',
    corresState: 'JOHOR',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BERKAHWIN',
    occupation: 'GURU',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2019-05-10'),
    arrivalPlace: 'SENAI',
    currPassportNo: 'E1234567A',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    spouseName: 'MUHAMMAD FAIZAL BIN ISMAIL',
    spouseDateOfBirth: new Date('1995-02-14'),
    spousePlaceOfBirth: 'JOHOR BAHRU',
    spouseNationality: 'MALAYSIA',
    spouseIdNumber: '950214-01-5678',
    marriedDate: new Date('2022-06-15'),
    marriedPlace: 'JOHOR BAHRU',
    isSpouseHasOtherNational: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'MUHAMMAD HAFIZ BIN KAMAL',
    fullNameOther: null,
    gender: 'M',
    dateOfBirth: new Date('1992-11-08'),
    placeOfBirth: 'MELBOURNE, AUSTRALIA',
    nationality: 'AUSTRALIAN',
    idType: 'PASSPORT',
    idNumber: 'N1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'KAMAL BIN OSMAN',
    permAddress1: 'NO. 12, JALAN AMPANG',
    permAddress2: 'TAMAN AMPANG UTAMA',
    permAddress3: null,
    permPostcode: '68000',
    permCity: 'AMPANG',
    permState: 'SELANGOR',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 12, JALAN AMPANG',
    corresAddress2: 'TAMAN AMPANG UTAMA',
    corresPostcode: '68000',
    corresCity: 'AMPANG',
    corresState: 'SELANGOR',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BUJANG',
    occupation: 'AKAUNTAN',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2021-03-20'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'N1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'NUR AISYAH BINTI IBRAHIM',
    fullNameOther: null,
    gender: 'F',
    dateOfBirth: new Date('2000-01-30'),
    placeOfBirth: 'JAKARTA, INDONESIA',
    nationality: 'INDONESIAN',
    idType: 'PASSPORT',
    idNumber: 'A1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'IBRAHIM BIN YUSOF',
    permAddress1: 'NO. 55, JALAN SULTAN ISMAIL',
    permAddress2: 'KAMPUNG BARU',
    permAddress3: null,
    permPostcode: '50250',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 55, JALAN SULTAN ISMAIL',
    corresAddress2: 'KAMPUNG BARU',
    corresPostcode: '50250',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BUJANG',
    occupation: 'PELAJAR',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2018-08-01'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'A1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'TAN WEI MING',
    fullNameOther: '陈伟明',
    gender: 'M',
    dateOfBirth: new Date('1988-05-12'),
    placeOfBirth: 'HONG KONG',
    nationality: 'HONG KONG SAR',
    idType: 'PASSPORT',
    idNumber: 'H1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'TAN AH KOW',
    permAddress1: 'NO. 168, JALAN PETALING',
    permAddress2: 'CHINATOWN',
    permAddress3: null,
    permPostcode: '50000',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 168, JALAN PETALING',
    corresAddress2: 'CHINATOWN',
    corresPostcode: '50000',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'CINA',
    religion: 'BUDDHA',
    maritalStatus: 'BERKAHWIN',
    occupation: 'AHLI PERNIAGAAN',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2015-12-01'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'H1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    spouseName: 'LIM MEI LING',
    spouseDateOfBirth: new Date('1990-08-25'),
    spousePlaceOfBirth: 'PENANG',
    spouseNationality: 'MALAYSIA',
    spouseIdNumber: '900825-07-1234',
    marriedDate: new Date('2018-02-14'),
    marriedPlace: 'KUALA LUMPUR',
    isSpouseHasOtherNational: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'RAJESH A/L KUMAR',
    fullNameOther: null,
    gender: 'M',
    dateOfBirth: new Date('1990-09-05'),
    placeOfBirth: 'CHENNAI, INDIA',
    nationality: 'INDIAN',
    idType: 'PASSPORT',
    idNumber: 'J1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'KUMAR A/L RAMAN',
    permAddress1: 'NO. 42, JALAN MASJID INDIA',
    permAddress2: 'LITTLE INDIA',
    permAddress3: null,
    permPostcode: '50100',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 42, JALAN MASJID INDIA',
    corresAddress2: 'LITTLE INDIA',
    corresPostcode: '50100',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'INDIA',
    religion: 'HINDU',
    maritalStatus: 'BUJANG',
    occupation: 'DOKTOR',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2017-06-15'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'J1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'FATIMAH BINTI HASSAN',
    fullNameOther: null,
    gender: 'F',
    dateOfBirth: new Date('1996-04-18'),
    placeOfBirth: 'DUBAI, UAE',
    nationality: 'UAE',
    idType: 'PASSPORT',
    idNumber: 'U1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'HASSAN BIN ALI',
    permAddress1: 'NO. 77, JALAN BANGSAR',
    permAddress2: 'BANGSAR BARU',
    permAddress3: null,
    permPostcode: '59100',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 77, JALAN BANGSAR',
    corresAddress2: 'BANGSAR BARU',
    corresPostcode: '59100',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BUJANG',
    occupation: 'ARKITEK',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2020-09-01'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'U1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'WONG KAH YONG',
    fullNameOther: '黄家勇',
    gender: 'M',
    dateOfBirth: new Date('1985-12-25'),
    placeOfBirth: 'TAIPEI, TAIWAN',
    nationality: 'TAIWANESE',
    idType: 'PASSPORT',
    idNumber: 'T1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'WONG CHEE KEONG',
    permAddress1: 'NO. 99, JALAN IMBI',
    permAddress2: 'BUKIT BINTANG',
    permAddress3: null,
    permPostcode: '55100',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 99, JALAN IMBI',
    corresAddress2: 'BUKIT BINTANG',
    corresPostcode: '55100',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'CINA',
    religion: 'KRISTIAN',
    maritalStatus: 'BERKAHWIN',
    occupation: 'PENGURUS IT',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2010-03-15'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'T1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    spouseName: 'CHEN SHU TING',
    spouseDateOfBirth: new Date('1988-06-10'),
    spousePlaceOfBirth: 'IPOH',
    spouseNationality: 'MALAYSIA',
    spouseIdNumber: '880610-08-5678',
    marriedDate: new Date('2015-11-11'),
    marriedPlace: 'IPOH',
    isSpouseHasOtherNational: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'NURUL HUDA BINTI ZAINAL',
    fullNameOther: null,
    gender: 'F',
    dateOfBirth: new Date('1999-02-28'),
    placeOfBirth: 'BRUNEI DARUSSALAM',
    nationality: 'BRUNEIAN',
    idType: 'PASSPORT',
    idNumber: 'B1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'ZAINAL BIN ABIDIN',
    permAddress1: 'NO. 33, JALAN KOTA KINABALU',
    permAddress2: 'TAMAN KINABALU',
    permAddress3: null,
    permPostcode: '88000',
    permCity: 'KOTA KINABALU',
    permState: 'SABAH',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 33, JALAN KOTA KINABALU',
    corresAddress2: 'TAMAN KINABALU',
    corresPostcode: '88000',
    corresCity: 'KOTA KINABALU',
    corresState: 'SABAH',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BUJANG',
    occupation: 'JURURAWAT',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2019-01-10'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'B1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'MOHD AZLAN BIN RAZAK',
    fullNameOther: null,
    gender: 'M',
    dateOfBirth: new Date('1993-08-15'),
    placeOfBirth: 'JEDDAH, SAUDI ARABIA',
    nationality: 'SAUDI ARABIAN',
    idType: 'PASSPORT',
    idNumber: 'S1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'RAZAK BIN MOHD',
    permAddress1: 'NO. 15, JALAN MASJID NEGARA',
    permAddress2: 'TASIK PERDANA',
    permAddress3: null,
    permPostcode: '50480',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 15, JALAN MASJID NEGARA',
    corresAddress2: 'TASIK PERDANA',
    corresPostcode: '50480',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BERKAHWIN',
    occupation: 'PENSYARAH',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2016-07-01'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'S1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    spouseName: 'ZAINAB BINTI OTHMAN',
    spouseDateOfBirth: new Date('1995-03-20'),
    spousePlaceOfBirth: 'KELANTAN',
    spouseNationality: 'MALAYSIA',
    spouseIdNumber: '950320-03-5678',
    marriedDate: new Date('2020-12-12'),
    marriedPlace: 'KOTA BHARU',
    isSpouseHasOtherNational: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'LEE JIA WEN',
    fullNameOther: '李佳文',
    gender: 'F',
    dateOfBirth: new Date('1997-06-08'),
    placeOfBirth: 'BEIJING, CHINA',
    nationality: 'CHINESE',
    idType: 'PASSPORT',
    idNumber: 'G1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'LEE CHONG WEI',
    permAddress1: 'NO. 188, JALAN PENANG',
    permAddress2: 'GEORGETOWN',
    permAddress3: null,
    permPostcode: '10050',
    permCity: 'GEORGETOWN',
    permState: 'PULAU PINANG',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 188, JALAN PENANG',
    corresAddress2: 'GEORGETOWN',
    corresPostcode: '10050',
    corresCity: 'GEORGETOWN',
    corresState: 'PULAU PINANG',
    corresCountry: 'MALAYSIA',
    race: 'CINA',
    religion: 'BUDDHA',
    maritalStatus: 'BUJANG',
    occupation: 'PEREKA GRAFIK',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2018-04-20'),
    arrivalPlace: 'PENANG',
    currPassportNo: 'G1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'MUTHU A/L SAMY',
    fullNameOther: null,
    gender: 'M',
    dateOfBirth: new Date('1991-10-10'),
    placeOfBirth: 'COLOMBO, SRI LANKA',
    nationality: 'SRI LANKAN',
    idType: 'PASSPORT',
    idNumber: 'L1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'SAMY A/L PILLAI',
    permAddress1: 'NO. 56, JALAN SENTUL',
    permAddress2: 'SENTUL',
    permAddress3: null,
    permPostcode: '51000',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 56, JALAN SENTUL',
    corresAddress2: 'SENTUL',
    corresPostcode: '51000',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'INDIA',
    religion: 'HINDU',
    maritalStatus: 'BERKAHWIN',
    occupation: 'PEGUAM',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2014-11-25'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'L1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    spouseName: 'KAVITHA A/P RAJAN',
    spouseDateOfBirth: new Date('1993-07-15'),
    spousePlaceOfBirth: 'KLANG',
    spouseNationality: 'MALAYSIA',
    spouseIdNumber: '930715-10-5678',
    marriedDate: new Date('2019-05-05'),
    marriedPlace: 'KLANG',
    isSpouseHasOtherNational: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'AMIRAH BINTI MOHD NOOR',
    fullNameOther: null,
    gender: 'F',
    dateOfBirth: new Date('1994-03-03'),
    placeOfBirth: 'CAIRO, EGYPT',
    nationality: 'EGYPTIAN',
    idType: 'PASSPORT',
    idNumber: 'EG1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'MOHD NOOR BIN AHMAD',
    permAddress1: 'NO. 22, JALAN SHAH ALAM',
    permAddress2: 'SEKSYEN 7',
    permAddress3: null,
    permPostcode: '40000',
    permCity: 'SHAH ALAM',
    permState: 'SELANGOR',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 22, JALAN SHAH ALAM',
    corresAddress2: 'SEKSYEN 7',
    corresPostcode: '40000',
    corresCity: 'SHAH ALAM',
    corresState: 'SELANGOR',
    corresCountry: 'MALAYSIA',
    race: 'MELAYU',
    religion: 'ISLAM',
    maritalStatus: 'BUJANG',
    occupation: 'PEGAWAI BANK',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2017-02-14'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'EG1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'DAVID NG CHEE HONG',
    fullNameOther: '黄志鸿',
    gender: 'M',
    dateOfBirth: new Date('1987-07-07'),
    placeOfBirth: 'NEW YORK, USA',
    nationality: 'AMERICAN',
    idType: 'PASSPORT',
    idNumber: 'US1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'NG BOON KEAT',
    permAddress1: 'NO. 123, JALAN DAMANSARA',
    permAddress2: 'DAMANSARA HEIGHTS',
    permAddress3: null,
    permPostcode: '50490',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 123, JALAN DAMANSARA',
    corresAddress2: 'DAMANSARA HEIGHTS',
    corresPostcode: '50490',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'CINA',
    religion: 'KRISTIAN',
    maritalStatus: 'BERKAHWIN',
    occupation: 'CEO',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2012-08-30'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'US1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'Y',
    anyOffence: 'T',
    anyConfination: 'T',
    spouseName: 'SARAH TAN MEI LIN',
    spouseDateOfBirth: new Date('1989-12-01'),
    spousePlaceOfBirth: 'KUALA LUMPUR',
    spouseNationality: 'MALAYSIA',
    spouseIdNumber: '891201-14-5678',
    marriedDate: new Date('2016-06-18'),
    marriedPlace: 'KUALA LUMPUR',
    isSpouseHasOtherNational: 'T',
    createdBy: 'SYSTEM',
  },
  {
    applicationType: 'PERKARA_15_2',
    fullName: 'PRIYA A/P SUBRAMANIAM',
    fullNameOther: null,
    gender: 'F',
    dateOfBirth: new Date('1995-11-22'),
    placeOfBirth: 'MUMBAI, INDIA',
    nationality: 'INDIAN',
    idType: 'PASSPORT',
    idNumber: 'IN1234567',
    relationWithEnrolledPerson: 'ANAK',
    enrolledPersName: 'SUBRAMANIAM A/L KRISHNAN',
    permAddress1: 'NO. 45, JALAN BRICKFIELDS',
    permAddress2: 'BRICKFIELDS',
    permAddress3: null,
    permPostcode: '50470',
    permCity: 'KUALA LUMPUR',
    permState: 'WILAYAH PERSEKUTUAN',
    permCountry: 'MALAYSIA',
    corresAddress1: 'NO. 45, JALAN BRICKFIELDS',
    corresAddress2: 'BRICKFIELDS',
    corresPostcode: '50470',
    corresCity: 'KUALA LUMPUR',
    corresState: 'WILAYAH PERSEKUTUAN',
    corresCountry: 'MALAYSIA',
    race: 'INDIA',
    religion: 'HINDU',
    maritalStatus: 'BUJANG',
    occupation: 'JURUTERA PERISIAN',
    countryOfResidence: 'MALAYSIA',
    isHoldingOtherNationality: 'Y',
    arrivalDate: new Date('2019-09-15'),
    arrivalPlace: 'KLIA',
    currPassportNo: 'IN1234567',
    isPreviouslyApply: 'T',
    isPrevMalaysianCitizenship: 'T',
    isApprovalLetterReceived: 'T',
    isTravelToOthCountry5y: 'T',
    anyOffence: 'T',
    anyConfination: 'T',
    createdBy: 'SYSTEM',
  },
]

async function main() {
  console.log('Seeding applicant data...')

  for (const applicant of applicantsData) {
    await prisma.applicant.create({
      data: applicant,
    })
  }

  console.log(`Successfully seeded ${applicantsData.length} applicant records.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
